server {
  # Lausche auf Port 80
  listen 80;

  # Liefere Daten nur ab diesem Verzeichnis aus
  root /usr/share/nginx/html;

  location / {
    # Default Dateien die ausgeliefert werden, wenn nur ein Pfad requested wird
    index index.html index.htm default.htm;

    # Erlaube das Anzeigen von Ordnerinhalten
    autoindex on;
  }
}
