server {
  # Lausche auf Port 80
  listen 80;
  server_name alpha.dev.sveneppler.de;

  # Liefere Daten nur ab diesem Verzeichnis aus
  root /usr/share/nginx/html/alpha/;

  location / {
    # Default Dateien die ausgeliefert werden, wenn nur ein Pfad requested wird
    index index.html index.htm default.htm;

    # Erlaube das Anzeigen von Ordnerinhalten
    autoindex on;
  }
}

server {
  # Lausche auf Port 80
  listen 80;
  server_name beta.dev.sveneppler.de;

  # Liefere Daten nur ab diesem Verzeichnis aus
  root /usr/share/nginx/html/beta/;

  location / {
    # Default Dateien die ausgeliefert werden, wenn nur ein Pfad requested wird
    index index.html index.htm default.htm;

    # Erlaube das Anzeigen von Ordnerinhalten
    autoindex on;
  }
}
